// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCraWqW5tDGTnAGCjxD0OMmNlbtG8x8A4',
    appId: '1:766639764665:web:17c65118a6be0b401e5768',
    messagingSenderId: '766639764665',
    projectId: 'quizflutter-1b592',
    authDomain: 'quizflutter-1b592.firebaseapp.com',
    storageBucket: 'quizflutter-1b592.firebasestorage.app',
    measurementId: 'G-BN36Q4PS5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-ZvoA-on8a60eFUbMTxvwlnY1EiVcfo',
    appId: '1:766639764665:android:264d0ab24af49b7e1e5768',
    messagingSenderId: '766639764665',
    projectId: 'quizflutter-1b592',
    storageBucket: 'quizflutter-1b592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwCONS4x6mSQQaveo94nEJ35ZfMm2rJiA',
    appId: '1:766639764665:ios:bb154710aa3822451e5768',
    messagingSenderId: '766639764665',
    projectId: 'quizflutter-1b592',
    storageBucket: 'quizflutter-1b592.firebasestorage.app',
    iosBundleId: 'com.example.swdquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwCONS4x6mSQQaveo94nEJ35ZfMm2rJiA',
    appId: '1:766639764665:ios:bb154710aa3822451e5768',
    messagingSenderId: '766639764665',
    projectId: 'quizflutter-1b592',
    storageBucket: 'quizflutter-1b592.firebasestorage.app',
    iosBundleId: 'com.example.swdquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCraWqW5tDGTnAGCjxD0OMmNlbtG8x8A4',
    appId: '1:766639764665:web:17c65118a6be0b401e5768',
    messagingSenderId: '766639764665',
    projectId: 'quizflutter-1b592',
    authDomain: 'quizflutter-1b592.firebaseapp.com',
    storageBucket: 'quizflutter-1b592.firebasestorage.app',
    measurementId: 'G-BN36Q4PS5E',
  );

}